name: swipe_action
description: "A simple flutter package to add swipe to reply functionality similar to that of Whatsapp."
version: 1.0.0
repository: https://github.com/rohan031/swipe_action

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

topics:
  - swipe-action
  - chat-reply

screenshots:
  - description: 'Example of swipe-action'
    path: example.gif


